### ISSUE TITLE
How to handle data with missing continuous outcome?

### ISSUE THREAD

**Issue by mpetukh** [tlverse/tmle3#89]
Hi,
we have a three-arm experiment with a loss to follow up. Chapter 7 from tlverse book https://tlverse.org/tlverse-handbook/tmle3.html says the following:

	Missing outcomes are efficiently handled by the automatic calculation (and incorporation into estimators) of inverse probability of censoring weights (IPCW); this is also known as IPCW-TMLE and may be thought of as a joint intervention to remove missingness and is analogous to the procedure used with classical inverse probability weighted estimators.
These steps are implemented in the process_missing function in tmle3:
processed <- [process_missing](http://tlverse.org/tmle3/reference/process_missing.html)(washb_data, node_list)
washb_data <- processed$data
node_list <- processed$node_list

I have been using the above until I realized that process_missing just drops the records with missing outcome and does not seem to produce IPCW.

So instead of using process_missing I defined learners for delta_Y in learner_list. This worked for a dichotomous outcome but did not work for a continuous outcome. 

Is using delta_Y the correct way to deal with missing dichotomous outcomes? And if yes, what should I do with missing continuous outcomes?

Thank you.

**Comment by rachaelvp** [comment]
Thanks for filing this issue! We’ll figure this out. Could you please send your R `sessionInfo` as well as a reproducible example, so we can more easily replicate the error your seeing and fix this?

**Comment by imalenica** [comment]
Resolved in https://github.com/tlverse/tmle3/tree/fix-ltfu
